name: Deploy to shinyapps.io

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      APP_DIR: "."
      SHINYAPPS_APPNAME: "SumSearch"

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install dependencies (incl. rsconnect)
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rsconnect

      - name: Show config
        run: |
          echo "Account: ${{ secrets.SHINYAPPS_ACCOUNT }}"
          echo "App dir: $APP_DIR"
          echo "App name: ${SHINYAPPS_APPNAME:-<default-to-folder>}"
          ls -la "$APP_DIR"

      - name: Preflight accountInfo
        env:
          SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
          SHINYAPPS_TOKEN:   ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET:  ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          Rscript -e 'options(repos=c(CRAN="https://cloud.r-project.org"));
          rsconnect::setAccountInfo(
            name   = Sys.getenv("SHINYAPPS_ACCOUNT"),
            token  = Sys.getenv("SHINYAPPS_TOKEN"),
            secret = Sys.getenv("SHINYAPPS_SECRET")
          );
          print(rsconnect::accountInfo())'

      # --- write FEC_API_KEY into .Renviron and ensure it's included in the bundle ---
      - name: Write .Renviron for deploy
        env:
          FEC_API_KEY: ${{ secrets.FEC_API_KEY }}
        run: |
          set -euo pipefail
          printf 'FEC_API_KEY=%s\n' "$FEC_API_KEY" > .Renviron
          echo "Wrote .Renviron (1 line)"
          # Make sure .Renviron is NOT excluded by .rscignore
          if [ -f .rscignore ]; then
            sed -i '/^\.Renviron$/d' .rscignore
          fi

      - name: Deploy to shinyapps.io
        env:
          SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
        run: |
          Rscript -e 'options(repos=c(CRAN="https://cloud.r-project.org"));
          app_dir  <- Sys.getenv("APP_DIR", unset=".")
          app_name <- Sys.getenv("SHINYAPPS_APPNAME", unset=basename(normalizePath(app_dir)))
          rsconnect::deployApp(appDir = app_dir,
                               appName = app_name,
                               forceUpdate = TRUE,
                               logLevel = "verbose")'
