name: Deploy to shinyapps.io

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      APP_DIR: "."
      SHINYAPPS_APPNAME: "SumSearch"

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install dependencies (incl. rsconnect)
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rsconnect

      - name: Show config
        run: |
          echo "Account: ${{ secrets.SHINYAPPS_ACCOUNT }}"
          echo "App dir: $APP_DIR"
          echo "App name: ${SHINYAPPS_APPNAME:-<default-to-folder>}"
          ls -la "$APP_DIR"

      - name: Preflight accountInfo
        env:
          SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
          SHINYAPPS_TOKEN:   ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET:  ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          Rscript -e 'options(repos=c(CRAN="https://cloud.r-project.org"));
          rsconnect::setAccountInfo(
            name   = Sys.getenv("SHINYAPPS_ACCOUNT"),
            token  = Sys.getenv("SHINYAPPS_TOKEN"),
            secret = Sys.getenv("SHINYAPPS_SECRET")
          );
          print(rsconnect::accountInfo())'

      # ---- The single deploy step (properly indented under steps) ----
      - name: Deploy to shinyapps.io (persist FEC_API_KEY)
        env:
          SHINY_APP_NAME: ${{ env.SHINYAPPS_APPNAME }}
          SHINY_ACCOUNT:  ${{ secrets.SHINYAPPS_ACCOUNT }}
          FEC_API_KEY:    ${{ secrets.FEC_API_KEY }}   # from GitHub repo secrets
        run: |
          set -euo pipefail
          Rscript -e 'rsconnect::deployApp(
            appDir     = Sys.getenv("APP_DIR", "."),
            appName    = Sys.getenv("SHINY_APP_NAME"),
            account    = Sys.getenv("SHINY_ACCOUNT"),
            forceUpdate= TRUE,
            envVars    = c(FEC_API_KEY = Sys.getenv("FEC_API_KEY"))  # persists on shinyapps.io
          )'
