name: Deploy to shinyapps.io

on:
  workflow_dispatch:   # manual trigger while we debug

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      APP_DIR: "."
      SHINYAPPS_APPNAME: "SumSearch"
      # ⚠️ You don’t commit .Renviron to Git (keep .Renviron in .gitignore). The Action creates it on-the-fly each deploy.

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      # Install deps via r-lib action (this is the reliable way)
      - name: Install dependencies (incl. rsconnect)
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: rsconnect
          needs: rsconnect

      - name: Show config
        run: |
          echo "Account: ${{ secrets.SHINYAPPS_ACCOUNT }}"
          echo "App dir: $APP_DIR"
          echo "App name: ${SHINYAPPS_APPNAME:-<default-to-folder>}"
          ls -la "$APP_DIR"

      - name: Preflight accountInfo
        env:
          SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
          SHINYAPPS_TOKEN:   ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET:  ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          Rscript -e 'options(repos=c(CRAN="https://cloud.r-project.org")); rsconnect::setAccountInfo(name=Sys.getenv("SHINYAPPS_ACCOUNT"), token=Sys.getenv("SHINYAPPS_TOKEN"), secret=Sys.getenv("SHINYAPPS_SECRET")); print(rsconnect::accountInfo())'

      # --- Minimal insertion begins ---
      - name: Create .Renviron from GitHub Secrets (and exclude from bundle)
        working-directory: ${{ env.APP_DIR }}
        shell: bash
        env:
          FEC_API_KEY: ${{ secrets.FEC_API_KEY }}
        run: |
          set -euo pipefail
          echo "FEC_API_KEY=${FEC_API_KEY}" > .Renviron
          # Ensure rsconnect does NOT upload .Renviron
          { test -f .rscignore && cat .rscignore || true; echo ".Renviron"; } | awk ' !x[$0]++ ' > .rscignore
          echo ".Renviron written and excluded via .rscignore"
      # --- Minimal insertion ends ---

      - name: Deploy to shinyapps.io
        env:
          SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
        run: |
          Rscript - <<'RSCRIPT'
          options(repos=c(CRAN="https://cloud.r-project.org"))
          app_dir  <- Sys.getenv("APP_DIR", unset=".")
          app_name <- Sys.getenv("SHINYAPPS_APPNAME", unset=basename(normalizePath(app_dir)))
          rsconnect::deployApp(appDir=app_dir, appName=app_name, forceUpdate=TRUE, logLevel="verbose")
          message("Deployment completed: https://", Sys.getenv("SHINYAPPS_ACCOUNT"), ".shinyapps.io/", app_name, "/")
          RSCRIPT
